-- ============================================================================
-- Table: users
-- Description: Stores core user credentials, profile data, and audit timestamps.
-- ============================================================================
CREATE TABLE users (
    -- Stable, non-sequential identifier generated by the application
    id UUID PRIMARY KEY,

    -- Public-facing user handle, constrained to 32 characters for UI boundaries
    username VARCHAR(32) NOT NULL,

    -- Secure password hash; raw passwords are never persisted
    password_hash VARCHAR(255) NOT NULL,

    -- Optional, currently unverified email address
    email VARCHAR(254),

    -- Hashed backup/recovery code used for account restoration
    recovery_code_hash VARCHAR(255) NOT NULL,

    -- Audit timestamp tracking when the account was originally registered
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Timestamp initialized at creation and maintained by the application on updates
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================================
-- Index: ux_users_username_lower
-- Description: Enforces case-insensitive uniqueness on usernames. This prevents
-- users from registering duplicate accounts like "Username" and "username".
-- ============================================================================
CREATE UNIQUE INDEX ux_users_username_lower
    ON users (LOWER(username));
