-- ============================================================================
-- Table: journeys
-- Description: Stores registered-user journeys independently from user accounts.
-- A user may own multiple journeys.
-- ============================================================================
CREATE TABLE journeys (
    -- Stable, non-sequential identifier generated by the application
    id UUID PRIMARY KEY,

    -- Registered user who owns this journey
    user_id UUID NOT NULL,

    -- Optional player-defined label used to distinguish multiple journeys
    name VARCHAR(100),

    -- Audit timestamp tracking when the journey was created
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Timestamp initialized at creation and maintained by the application on updates
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_journeys_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);

-- ============================================================================
-- Index: ix_journeys_user_id
-- Description: Supports retrieving all journeys owned by a registered user.
-- ============================================================================
CREATE INDEX ix_journeys_user_id
    ON journeys (user_id);